default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  reconnect: true
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: new_vertex_dev
  username: root
  password: root

staging:
  <<: *default
  database: new_vertex_staging
  username: 
  password: 

test:
  <<: *default
  database: new_vertex_test
  username: root
  password: root

production:
  <<: *default
  database: new_vertex_production
  username: 
  password: 
